apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
  namespace: pmotrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: redmine:5
        ports:
        - containerPort: 3000
          name: redmine-port
        env:
        - name: REDMINE_DB_POSTGRES
          value: "postgres-service"
        - name: REDMINE_DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: REDMINE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  namespace: pmotrack
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  selector:
    app: redmine
